# -*- coding: utf-8 -*-
"""preprocessGroupNormalVids .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWqkNroqbhrfpIOyrR7FQPJVU2Rp0QZq
"""

import os, sys
from os import listdir
import shutil
import pandas as pd

#create normal class based on the labels given in DCSASS dataset
datasetDir = 'DCSASS Dataset/'
classes = os.listdir(datasetDir)
OUT = 'DCSASS Dataset/Normal/'
if not os.path.isdir(OUT):
	os.mkdir(OUT)

for folder in classes:
	label = pd.read_csv("Labels/"+ folder +".csv", header = None)
	FOLDER = datasetDir + folder + '/'
	for i in range(len(label)):
		if label[2][i] == 0:
			PATH = FOLDER + label[0][i] + '.mp4'
			dest = shutil.move(PATH, OUT, copy_function = shutil.copytree) 
			print(dest)