# -*- coding: utf-8 -*-
"""preprocessMoveVidsFromSubfolder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CCvj4qtnpe9bUwbdvtrISagCABN0OG00
"""

import os, sys
from os import listdir
import shutil

datasetDir = 'DCSASS Dataset/'

#move all video clips from the subfolders into the shoplifting folder
for folder in os.listdir(datasetDir):
	folder_url = datasetDir + folder + '/'
	for subfolder in os.listdir(folder_url):
		subfolder_url = folder_url + subfolder + '/'
		for clip in os.listdir(subfolder_url):
			clip_url = subfolder_url + clip
			shutil.move(clip_url, folder_url, copy_function = shutil.copytree)
   
		#remove the empty folder after clips are moved out
		os.rmdir(subfolder_url)